### ISSUE TITLE
Example of creating a new workbook with only *some* worksheets from the current workbook

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js-docs-reference#1032]
The samples in the docs only talk about pre-populating the created workbook with the **full contents** of the current workbook.

Is it possible to only copy **some** specific worksheets from the current workbook into the new one? Can we have a sample for that please?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b93905-3b88-d509-71da-01d29ad5ce90
* Version Independent ID: 1c68b9ac-b012-3101-44b4-39a9db47a245
* Content: [excel package - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@wh1t3cAt1k Thanks for asking about this.

@lumine2008 Can you take a look?

Thanks.

**Comment by alison-mk** [comment]
Hi @wh1t3cAt1k, thanks for submitting a question. The [Workbook.insertWorksheetsFromBase64](https://docs.microsoft.com/javascript/api/excel/excel.workbook?view=excel-js-preview#insertWorksheetsFromBase64_base64File__options_) method allows you to copy all or some of the worksheets from one workbook into another workbook. The conceptual article section for the insert worksheets API is here: (Insert a copy of an existing workbook into the current one)[https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-workbooks#insert-a-copy-of-an-existing-workbook-into-the-current-one].

The insertWorksheetsFromBase64 method uses the sheetNamesToInsert property of the (Excel.InsertWorksheetOptions interface)[https://docs.microsoft.com/javascript/api/excel/excel.insertworksheetoptions?view=excel-js-preview], which takes sheet names. You can specify which worksheets to insert with this property.

The code samples in our reference and conceptual documentation for this method insert all worksheets, because they are general code samples and we don't know what your worksheets might be named.  

We do have an Office Add-ins PnP for the insertWorksheetsFromBase64 method and it inserts one worksheet by name from a source workbook. This PnP provides a source workbook, and then it inserts the *Template* worksheet from the source workbook into the new workbook with this line: `sheetNamesToInsert: ["Template"]`. See the PnP code sample here: (Insert an external Excel file and populate it with JSON data)[https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/excel-insert-file].

Let me know if you have any additional questions. 

Cheers, 
Alison

**Comment by wh1t3cAt1k** [comment]
Thank you very much! It is helpful

**Comment by alison-mk** [comment]
Hi @wh1t3cAt1k, apologies for the delay. Thank you for your patience. 

My internal research indicates that yes, this is possible using the [getFileAsync() method](https://docs.microsoft.com/javascript/api/office/office.document?view=common-js-preview#office-office-document-getfileasync-member(1)). Once you've edited the base64-encoded string, you can use the Excel.createWorkbook method described in the [Create a workbook](https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-workbooks#create-a-workbook) article section to generate a new workbook with specific worksheets.

If you have any programming questions about file slicing with the `getFileAsync()` method, we suggest consulting [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) to see if your question has already been asked or ask a new question. Stack Overflow has an active community of developers that regularly provide feedback and guidance. 

If the existing method doesn't meet the needs of your scenario, we recommend submitting a feature request via [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). We use Microsoft 365 Developer Platform Ideas to prioritize community requests for additions to the product. If the community upvotes your request, it's more likely to be added to the add-ins platform.

Since this isn't a bug, I'm going to close this issue.

Cheers, 
Alison
