### ISSUE TITLE
Getting the selected shape?

### ISSUE THREAD

**Issue by LukeOwlclaw** [OfficeDev/office-js-docs-reference#1052]
As demonstrated by ``getSelectedSlideIndex()`` from sample https://raw.githubusercontent.com/OfficeDev/office-js-snippets/prod/samples/powerpoint/preview-apis/tags.yaml it is easy to determine the currently selected slide.
Is there an option to get the currently selected shape(s)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4666676e-3918-dafc-4846-efbf7363aabf
* Version Independent ID: eba73286-6426-887e-477a-ed9f641dac0f
* Content: [PowerPoint.Shape class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shape?view=powerpoint-js-preview)
* Content Source: [docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shape.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shape.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@LukeOwlclaw Thanks for asking about this.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
Thanks for your interest. We use this repo to track problems in the documentation. This kind of "How do I do such and such" question is best posted to Stack Overflow, where a much larger set of Office add-in developers will see it and benefit from any answers that you get. 

In the meantime, the [getSelectedDataAsync](https://docs.microsoft.com/javascript/api/office/office.document?view=excel-js-preview#getSelectedDataAsync_coercionType__options__callback_) method of the Common APIs will probably not work because it requires a [CoercionType](https://docs.microsoft.com/en-us/javascript/api/office/office.coerciontype?view=excel-js-preview) and there is no CoercionType for shapes. But you could try using the CoercienType for images and see if that works. 

Alternatively, in the PowerPoint-specific APIs, there is a now in preview a [ShapeCollection](https://docs.microsoft.com/javascript/api/powerpoint/powerpoint.shapecollection?view=powerpoint-js-preview) class that has a `getItem` and `getItemAt` methods. Perhaps these could be used in your scenario.

I will close this since it is not really a documentation issue. But if you have further questions, you can raise them on Stack Overflow. Be sure to tag the question `office-js`.
