### ISSUE TITLE
Method to change format of Xlsx to Microsoft 2007-13

### ISSUE THREAD

**Issue by Raks-coder** [OfficeDev/office-js-docs-reference#1113]
[Enter feedback here]

Hi,
I was going through the docs but couldn't find a method to change format to Microsoft 2007-13. Could you please tell if there is any such way to automate this?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b93905-3b88-d509-71da-01d29ad5ce90
* Version Independent ID: 1c68b9ac-b012-3101-44b4-39a9db47a245
* Content: [excel package - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by RuoyingLiang** [comment]
@Rick-Kirkham , could you help to take a look at this request?

**Comment by AlexJerabek** [comment]
Hi @Raks-coder,
Thank you for the question. There is not an API to make this file format change. There appear to be some solutions on [Stack Overflow](https://stackoverflow.com/search?q=convert+xlsx+to+xls) for converting to older file types. Hopefully, one of them will work in the automated system you have in mind.
Since there's nothing actionable with the Office JavaScript APIs, I'm going to close this issue.
