### ISSUE TITLE
Update Fields in Word document with officejs after changing CustomDocumentProperty

### ISSUE THREAD

**Issue by klingu** [OfficeDev/office-js-docs-reference#1125]
Hi all,

I'm looking for some help and I can't find the answer online.

I'm building a Word Add-in with officejs 1.3. 
On this Add-in the user fills-out a form. With the given data I override or add these to CustomDocumentProperties.

The 'Fields' on the document is not updatet and keep showing the old data. Even after closing and opening the document. Only when I right-click on the 'Field' and choose for 'Update Field' the updatet value is shown.

I can't use Macro's because it has to work on a Mac as well.

In VSTO, we can easily update fields of a Word document using c# code:

`_wordApplication.ActiveDocument.Fields.Update();`

But how do I manage this with officejs?

Thanks for helping me out!

Jeffrey

**Comment by klingu** [comment]
Hi team, 

Today it is been a month I've posted this issue. I see it has been assigned to various people, unfortunately no response or a solution yet. Is there any update.

Thanks in advance ;-)

Jeffrey

**Comment by ElizabethSamuel-MSFT** [comment]
@klingu Apologies for the delay. Unfortunately, office-js doesn't currently include any API to manage Fields in Word.

However, the team is actively working on implementing that feature and we hope to have a preview out in Word on the web. We don't currently have any timelines for this but we usually provide updates on upcoming API availability during the [Office Add-ins community call](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-ins-community-call) so that can be a good resource.

We hope that you try out the feature when it's available and let us know your feedback.

I'll go ahead and close this issue now. But do let us know if you have further questions on this and we can reopen it.

Thanks.
