### ISSUE TITLE
insertWorksheetsFromBase64 don't support in current version

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs-reference#1134]
[Enter feedback here]
when I use insertWorksheetsFromBase64  method in excel,error happened.
error message:
insertWorksheetsFromBase64 don't support in current version

![1](https://user-images.githubusercontent.com/3182964/150262518-9e473cdd-ff89-45fc-99d5-e435e5646fac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ae8d77-4f97-c7a8-be22-4386c805e1df
* Version Independent ID: fb673dd7-9a9f-588d-7845-6a8ff4d1a5ce
* Content: [Excel.Workbook class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.workbook?view=excel-js-preview#excel-excel-workbook-insertworksheetsfrombase64-member(1))
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.workbook.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.workbook.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @hengchengfei, thanks for submitting this issue. The error you're seeing is expected because `insertWorksheetsFromBase64` isn't available for Excel 2019. The `insertWorksheetsFromBase64` API is part of the ExcelApi 1.13 requirement set. In our reference documentation, you can see which requirement set an API is assigned to by scrolling down to the remarks section: [Workbook.insertWorksheetsFromBase64(base64File, options)](https://docs.microsoft.com/javascript/api/excel/excel.workbook?view=excel-js-preview#excel-excel-workbook-insertworksheetsfrombase64-member(1)).

See the following screenshot for reference: 
![image](https://user-images.githubusercontent.com/7977793/151082036-572c562e-079a-4f99-9f6b-a0d435f52394.png)

Office 2019 (including Excel 2019) only supports requirement sets up to ExcelApi 1.8. See [Office client application and platform availability for Office Add-ins: Excel](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#excel) for a complete list of requirement set availabilities with each version of Excel.

I'm going to close this issue because the error is anticipated. Let us know if you have any more questions. 

Thanks, 
Alison
