### ISSUE TITLE
Add methos doesnt allow a refrence to a RangeAreas object

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js-docs-reference#1165]
The Add method on the names collection:
add(name: string, reference: Range | string, comment?: string): Excel.NamedItem;

Allows a reference that points to a range, but not a rangeAreas object. This means you can not create a defined name, that points to, for example: A:A10, B1:B5.  (A selection of multiple ranges).

This seems an unnecessary limitation.

Edwin
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423ae709-8187-2524-1a4b-050fbf02a4ee
* Version Independent ID: aeb1d0c2-cddb-0c67-571d-c518b9cd3ec3
* Content: [Excel.NamedItemCollection class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.nameditemcollection?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.nameditemcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.nameditemcollection.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @EdwinStraver,

Thank you for this suggestion. I'll relay it to the product team. In order to get more attention to this feature, I'd suggest creating an Idea in our Tech Community: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform. Be sure to include your scenario so we can better understand your specific needs.

On Tech Community, the community can upvote ideas they would also like. Our feature crews regularly check that space and use it to help prioritize new work.

I'm going to close this issue, since there's isn't an action we can take in the documentation.
