### ISSUE TITLE
Add `isDialog` property to Office.Context

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js-docs-reference#1171]
When my Outlook add-in opens a dialog, my code can see that `Office.context.isDialog` is set to `true`. I want to detect whether Office.js is running in a dialog so that I know only limited Office APIs are available. For this, I'm currently using `Office.context.isDialog`.

Could this property be documented and supported so that I have the confidence it will still be there in the future? I'd especially like this defined in[ the types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/office-js) 🙂

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1424764-ecfa-4f54-7e20-a873e9f52698
* Version Independent ID: 3f369a22-39b1-06b1-faea-eac921097824
* Content: [Office.Context interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=common-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.context.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.context.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @markdon,

Thanks for raising this issue. @Rick-Kirkham, could you please investigate this sample creation and documentation improvement?

**Comment by Rick-Kirkham** [comment]
I'm researching to see if there's any reason that the engineers deliberately choose to not document this. But I suspect it's just an oversight.

**Comment by Rick-Kirkham** [comment]
Well, it turns out that this is _not_ an oversight. It was originally created for internal testing purposes, but it doesn't work reliably outside of certain constrained testing scenarios. We don't support using it in add-ins. Hence, we don't document it. 

Perhaps as a workaround, your code could call an API that is not supported in the dialog and then catch the error that would be thrown in the dialog. 

Since there is no action item here for the documentation, I will close this issue, but you can still add comments @mention me.

**Comment by markdon** [comment]
@Rick-Kirkham TBH, I thought it likely to be undocumented on purpose. Thanks for looking in to it!
