### ISSUE TITLE
Is it possible to detect On-Premise and non-On-Premise accounts using their supported mailbox API version?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-reference#1267]
Can we determinne if a system supports REST/GRAPH using the mailbox version supported by the environment? Is the following equation/algorithm correct ? 

If system/environment supports Mailbox 1.6, then this is either M365 or an Exchange Online account. 
If system/environment supports Mailbox 1.5 and not Mailbox 1.6, then this is an On-Premise account.

Is the above algorithm usable to determine if the environment is on-premise or not?

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19f4fc6-2b5a-addf-058a-f7b671d15880
* Version Independent ID: ed3662f0-45ff-671d-afc3-17c44930b9bd
* Content: [Outlook JavaScript API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=common-js-preview)
* Content Source: [docs/requirement-sets/outlook/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/requirement-sets/outlook/outlook-api-requirement-sets.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Hi @glr0221,

Thank you for your question. I believe this is related to our recent discussion in #1266. Because the requirement sets you listed above refer to the JS APIs and are different from the Graph API, I would suggest going with your plan to use the accountType property to determine whether the mailbox is hosted on an on-prem server or on Exchange Online.

If your question is related to the previous post, let me know if I can go ahead and close this issue. We can continue our discussion in the other post if you require further assistance.

Thank you.

**Comment by glr0221** [comment]
Hello @samantharamon 

Thank you for your responses.  Yes this is related to the other question I have in #1266. We can close this one.

Thank you.

**Comment by samantharamon** [comment]
Thanks, @glr0221.
