### ISSUE TITLE
Currently name property is read only - how to update name property in order to change regional settings?

### ISSUE THREAD

**Issue by m14d3n** [OfficeDev/office-js-docs-reference#1297]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22f11f1-42d4-91d7-b43d-fd62ee8a711c
* Version Independent ID: ce8633d5-7b61-0f99-782f-a5a57ce44927
* Content: [Excel.CultureInfo class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.cultureinfo?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.cultureinfo.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.cultureinfo.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @m14d3n, thank you for submitting a question. The Excel JavaScript API doesn't currently offer the option to change the language and culture settings of the application. The article section [Workbook: Access application culture settings](https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-workbooks#access-application-culture-settings) describes the features the `CultureInfo` object offers. 

For feature requests, we recommend submitting via [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). We use Microsoft 365 Developer Platform Ideas to prioritize community requests for additions to the product. If the community upvotes your request, it's more likely to be added to the add-ins platform.

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Cheers, 
Alison
