### ISSUE TITLE
Statud date

### ISSUE THREAD

**Issue by alrdiaz** [OfficeDev/office-js-docs-reference#1694]
[¿How is the way to get the status date of a project using office.js in a add in for Ms Project?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a095abf-378e-1f57-a339-c4fc293f5cc7
* Version Independent ID: 76c920ea-8e9c-ab83-1814-44efa22d879e
* Content: [Office.ProjectProjectFields enum - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/office/office.projectprojectfields?view=common-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.projectprojectfields.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.projectprojectfields.yml)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @alrdiaz,

Thanks for reaching out. I'm not quite sure what your question is. From the documentation page linked in the article, you can get the start date through the [Document.getProjectFieldAsync](https://learn.microsoft.com/en-us/javascript/api/office/office.document?view=common-js-preview#office-office-document-getprojectfieldasync-member(1)) method. Here's a code snippet showing how you'd do that.

```
Office.context.document.getProjectFieldAsync(Office.ProjectProjectFields.Start, (result) => {
      if (result.status === Office.AsyncResultStatus.Succeeded) {
        document.getElementById("date-text").textContent = result.value.fieldValue;
      } else {
        console.log(result.error);
      }
    });
```

Please let me know if this helps.

**Comment by alrdiaz** [comment]
Hi, Alex thanks for the attention I’m talking about status date 

https://support.microsoft.com/en-us/office/set-the-status-date-for-project-reporting-ef4ad175-b219-456a-8f62-2eef97a3c8ce

https://images.app.goo.gl/WdJSbN61fc8RQC8PA

**Comment by AlexJerabek** [comment]
Thanks for the clarification. Based on the current APIs, I don't think that field is supported. I'll double-check internally.

I would recommend asking this question on Stack Overflow (with the office-js tag) to see if there's a workaround. You could also visit the [Project Tech Community](https://techcommunity.microsoft.com/t5/project/ct-p/Project) and see if there's another solution for your scenario. You can push for support in for this in Office JS through the [Microsoft Developer Platform Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform), but I'll be honest and say there's not any current investment in Project from Office JS.

I'm going to close this issue, since there's nothing actionable from the documentation side.
