### ISSUE TITLE
Office.MailboxEnums.RecipientType DistributionList

### ISSUE THREAD

**Issue by ThanhVuNTQ** [OfficeDev/office-js-docs-reference#1803]
Hello,

I have a question regarding the functionality of DistributionLists in an email system. I would like to know if it is possible for a DistributionList to include external email addresses that are outside of the organization.

I'm curious to understand if a DistributionList can be configured to include both internal and external email addresses, or if it is limited to internal addresses only.

Your insights and clarification on this matter would be greatly appreciated. Thank you for your assistance!

![image](https://github.com/OfficeDev/office-js-docs-reference/assets/152581121/297334c6-2ef6-4c7b-9db0-d16318dd2eda)

**Comment by samantharamon** [comment]
Hi @ThanhVuNTQ,

Apologies for the delayed response. External contacts can be added to a distribution list, but you may need to configure the policies of the distribution list so that external contacts receive emails sent to the list. For more information, see [Add a user or contact to a Microsoft 365 distribution group](https://learn.microsoft.com/microsoft-365/admin/email/add-user-or-contact-to-distribution-list).

For future reference, please note that issues created in this GitHub repository are for Office Add-ins documentation bugs and feedback. Please post any Outlook/Exchange product questions to the [Microsoft Support Community](https://answers.microsoft.com/) page.
