### ISSUE TITLE
`RequestedWidth` for Web

### ISSUE THREAD

**Issue by sakgoyal** [OfficeDev/office-js-docs-reference#1817]
How do I specify the `RequestedWidth` Property in the manifest xml file for outlook add ins? 
The Outlook app on the web doesnt seem to support resizing the taskpane manually either. is this something I can control?

**Comment by AlexJerabek** [comment]
Hi @sakgoyal,

Thanks for reaching out. There is no way to programmatically set the width of an add-in taskpane. Please upvote the feature suggestion on [Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/control-width-of-office-js-add-ins-outlook-task-pane/idi-p/3285899) to help us prioritize feature additions.

Since there's nothing actionable to do in the docs, I'll close this issue. Please let us know if you have any other questions.

@exextoc, FYI
