### ISSUE TITLE
OfficeJS Word > Building Blocks

### ISSUE THREAD

**Issue by Zeziroth** [OfficeDev/office-js-docs-reference#1889]
**Describe your scenario**
I cannot use BuildingBlock in my Web-AddIn....

**Which APIs or add-in features?**
Can someone say if or when support for building blocks will be integrated?

**Comment by AlexJerabek** [comment]
Hi @Zeziroth,

Thank you for reaching out. We have no timeline for the adding the Building Blocks feature to the Word JavaScript APIs. Depending on your scenario, you might be able to use [ContentControls](https://learn.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview) to a similar effect.

Please create or upvote a request for this feature in the [M365 Developer Platform Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). There, we can gauge the community's interest of new features and prioritize accordingly.  Let me also tag @zhenhuangMSFT so the Word feature crew is aware of your request.

Since there's nothing actionable to be done in the documentation here, I'm going to close this issue. If you have any other questions, I'm happy to help.
