### ISSUE TITLE
请问如何在右键邮件是添加Menu 

### ISSUE THREAD

**Issue by Git-title** [OfficeDev/office-js-docs-reference#1972]
在VSTO版本是可以右键邮件时添加Menu的，但在web版本的文档上并没有看到相关的拓展点，以及上方主页，查看，帮助后面我想再加一个tab页 如何添加，是否有这样的拓展点？这对我很重要

**Comment by Rick-Kirkham** [comment]
Bing Translator version: 

> "In the VSTO version, you can add Menu when you right-click on the email, but I don't see the relevant extension points on the web version of the document, as well as the upper home page, view, help, I want to add another tab page How to add, is there such an extension point? It's important to me"

**Comment by AlexJerabek** [comment]
Hi @Git-title,

Thank you for contacting us. Based on the information in the article, [ExtensionPoint element](https://learn.microsoft.com/javascript/api/manifest/extensionpoint?view=outlook-js-preview), menus are only available in Excel, Word, and PowerPoint (not Outlook mail items). You can upvote the [feature request that is in TechCommunity](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/context-menus-in-outlook-web-add-ins/idi-p/3065601). That will help us prioritize adding new features. 

I will be closing this issue because there is nothing that can be done in the documentation.
