### ISSUE TITLE
typeerror: cannot read properties of undefined (reading 'microphone')

### ISSUE THREAD

**Issue by YesLetsGo** [OfficeDev/office-js-docs-reference#1981]
Everything works fine, while using office.js by this:
<script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js" type="text/javascript"></script>

But when I install "office-js" locally via the NPM package by following command (https://github.com/OfficeDev/office-js):
npm install @microsoft/office-js --save

And using my office.js like this:
<script type="text/javascript" src="https://127.0.0.1:3000/Scripts/Office/1/office.js"></script>

I get typeerror: cannot read properties of undefined (reading 'microphone').

After commenting out the code responsible for reading microphone permissions, the plugin and all its functions work properly. 
Why is this happening?

**Comment by AlexJerabek** [comment]
Hi @YesLetsGo,

The most recent version of office-js is available on the [CDN](https://appsforoffice.microsoft.com/lib/1/hosted/office.js). Since the [DevicePermission requirement set](https://learn.microsoft.com/javascript/api/requirement-sets/common/device-permission-service-requirement-sets) was recently added, it's likely that update has not yet propagated to the NPM package. This is one of the reasons we recommend always using the [CDN version in your project](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn).

The NPM version should catch up soon. Regardless, the current guidance is that Office Add-ins should always reference the library stored in our CDN. I'll tag @gergzk for awareness of this matter.

I'm going to close this issue, since there's nothing actionable to be done in the documentation. Please let me know if you need further assistance.
