### ISSUE TITLE
how to show two buttons in notification message

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-reference#1984]
this code is simple show a notification how can I add a button with this notification like in this Image
![image](https://github.com/OfficeDev/office-js-docs-reference/assets/134502135/ffa1c1a4-7f3d-4b28-9d25-fa1330786229)

for more info [see this](https://youtu.be/qYFzS4_6S80?si=6bm7kq1FL_P4UCuM&t=125)

 ```
let message: Office.NotificationMessageDetails;
     message = {
            type: Office.MailboxEnums.ItemNotificationMessageType.InformationalMessage,
            message: "Enter Your Message here",
            icon: "Icon.80x80",
            persistent: true,
        };
       // Show a notification message.
    Office.context.mailbox.item.notificationMessages.replaceAsync("ActionPerformanceNotification", message);
```

**Comment by AlexJerabek** [comment]
Hi @junaid042,

Currently, only one action per notification message is supported (as documented in the [NotificationMessageDetails.actions description](https://learn.microsoft.com/javascript/api/outlook/office.notificationmessagedetails?view=outlook-js-preview#outlook-office-notificationmessagedetails-actions-member). However, you could [add a second notification](https://learn.microsoft.com/javascript/api/outlook/office.notificationmessages?view=outlook-js-preview#outlook-office-notificationmessages-addasync-member(1)) to give your users another option.

To request support for additional notification options, please post your idea (or upvote an existing one) on the [Microsoft 365 Developer Platform Tech Community](https://aka.ms/m365dev-suggestions).

I'm going to close this issue, since there's nothing actionable to be done in the documentation. Please let us know if you have any other questions.

**Comment by junaid042** [comment]
@AlexJerabek  thank you for always helping me 😍
