### ISSUE TITLE
page number

### ISSUE THREAD

**Issue by XWANG0224** [OfficeDev/office-js-docs-reference#2111]
is there any way I can get the page number where a selected paragraph is loacated?
and is there any way I can add the page number into the footer

**Comment by AlexJerabek** [comment]
Hi @XWANG0224,

Thank you for the questions. @ElizabethSamuel-MSFT, are these scenarios supported in the Word API at this time?

**Comment by ElizabethSamuel-MSFT** [comment]
@XWANG0224 Thanks for your question. For a dynamic solution, you can use the Page field.

For example, the following code inserts a page field before the selected text in the document. The user should see the number of the current page if the field is set to show the result instead of the code.

```ts
async function rangeInsertPageField() {
  // Inserts a Page field before selection.
  await Word.run(async (context) => {
    const range: Word.Range = context.document.getSelection().getRange();

    const field: Word.Field = range.insertField(
      Word.InsertLocation.before,
      Word.FieldType.page
    );

    field.load("result,code");
    await context.sync();

    if (field.isNullObject) {
      console.log("There are no fields in this document.");
    } else {
      console.log("Code of the field: " + field.code, "Result of the field: " + JSON.stringify(field.result));
    }
  });
}
```

**Console logs**

In this case, I'd selected text on the second page of my document.

```text
Code of the field:  PAGE  \* MERGEFORMAT 

Result of the field: {"hyperlink":"","isEmpty":false,"style":"Normal","styleBuiltIn":"Normal","text":"2"}
```

In [Script Lab](https://learn.microsoft.com/office/dev/add-ins/overview/explore-with-script-lab), you can use the [Manage fields](https://github.com/OfficeDev/office-js-snippets/blob/main/samples/word/50-document/manage-fields.yaml) sample to experiment with the JS field APIs.

You can try something like the following to insert the Page field in the footer.

```ts
async function addFooter() {
  await Word.run(async (context) => {
    context.document.sections
      .getFirst()
      .getFooter("Primary")
      .insertText(
        "",
        Word.InsertLocation.replace)
      .getRange()
      .insertField(
        Word.InsertLocation.replace,
        Word.FieldType.page
      );

    await context.sync();
  });
}
```

In Script Lab, you can use the [Insert headers and footers](https://github.com/OfficeDev/office-js-snippets/blob/main/samples/word/25-paragraph/insert-header-and-footer.yaml) sample to experiment with header/footer APIs.

For more about the Page field, see [Field codes: Page field](https://support.microsoft.com/office/aef4b341-db2a-4bd9-9f97-2d3b97a89b67).

For more about fields in general, see [Insert, edit, and view fields in Word](https://support.microsoft.com/office/c429bbb0-8669-48a7-bd24-bab6ba6b06bb). Note that the client/platform availability of the Page field depends on if it's supported in the Word UI on that client/platform.

Let us know if this helps or if you have further questions.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@XWANG0224 Thanks for letting us know that my response helped.

As for the cross-reference field showing the code instead of the result, try the following in the Word UI.

1. Open the context menu (e.g., by right-clicking on the field).
2. Select the option to "Toggle Field Codes".

Instead of seeing the field's code, you should now see the results - `123` in your case.

As for using the ref [field](https://learn.microsoft.com/javascript/api/word/word.field) in your add-in code, you should be able to adapt the `rangeInsertPageField` function provided in my earlier response. For example, instead of [FieldType](https://learn.microsoft.com/javascript/api/word/word.fieldtype).page, use FieldType.ref. When you load the field's result and code properties, you should get the information you're looking for.

For more about the Ref field, see [Field codes: Ref field](https://support.microsoft.com/office/b2531c23-05d6-4e3b-b54f-aee24447ceb2).

Hope this helps.

**Comment by ElizabethSamuel-MSFT** [comment]
@XWANG0224 I think I understand what you're asking for. So if you use the UI to create the cross-reference, then the API is able to get the field's codes (which includes this hidden bookmark that links to the selected paragraph). However, paragraphs don't usually have bookmarks unless they're items like "Title". You may be able to create a bookmark that you can then reference (e.g., using [Range.insertBookmark](https://learn.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#word-word-range-insertbookmark-member(1))). But I'll continue digging into this and see what else I can find.

**Comment by ElizabethSamuel-MSFT** [comment]
@XWANG0224 Were you able to make any progress on this on your own? Thanks.
