### ISSUE TITLE
How can I prevent an Outlook add-in from opening in the message reading popup?

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#2141]
Problem Description
I am developing an Add-In for Microsoft Outlook. I would like the Add-In not to be automatically opened in the message reading popup (when the user opens an email). The goal is to limit the loading of the Add-In to only the main window or specific contexts.

Current Behavior
Currently, the Add-In also automatically loads in the email reading popup, which is not necessary for our use case.

Desired Behavior
The Add-In should not automatically open in the reading popup, but only in the required main contexts (for example, the main Outlook window).

Steps to Reproduce

Open Outlook.
Enable the Add-In.
Double-click an email to open it in the reading popup.
Observe that the Add-In is also loaded in the popup.
Possible Solutions

Use the Add-In manifest settings to specify the contexts in which it should be loaded.
Please properly configure your Add-In commands or components to avoid loading in the popup.

**Comment by alison-mk** [comment]
Hi @CodeCube0, thank you for submitting! We use Github issues to report bugs with the product, and it looks like you are asking a more general programming question. For programming questions, we suggest you go to [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) and see if your question has already been asked or ask a new question. Stack Overflow has an active community of developers that regularly provide feedback and guidance. 

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Alison
