### ISSUE TITLE
RequestContext.trace is not properly documented

### ISSUE THREAD

**Issue by Thiez** [OfficeDev/office-js-docs-reference#257]
The `OfficeExtension.Error` object (for Word, Excel, and OneNote) has a `traceMessages` member, which is a string array. The Word error.md page shows an example where it creates these trace messages, by calling `context.trace` (short example: `Word.run(function(context) { context.trace("Hello world"); })`). However, reference/word/requestcontext.md contains no mention of the `trace` method. A [search](https://github.com/OfficeDev/office-js-docs/search?q=trace&type=Code) for the word "trace" reveals it to be mentioned only in the error.md pages for Word, Excel, and OneNote, and only the Word error.md page reveals how to use context.trace. I would expect this method to be documented on the requestcontext.md page also. In addition, if `traceMessages` is available in other applications (e.g. PowerPoint, Outlook) it should be documented on those pages as well.

**Comment by AlexJerabek** [comment]
Hi @Thiez,
Sorry about the long delay on this. Since this issue was raised, we have redesigned our reference documentation experience. It is (hopefully) more clear now [OfficeExtension.Error.traceMessages](https://docs.microsoft.com/javascript/api/office/officeextension.error#tracemessages) relates to [OfficeExtension.ClientRequestContext.trace](https://docs.microsoft.com/javascript/api/office/officeextension.clientrequestcontext#trace-message-).

I'll close the issue, but pleae reopen it if the documentation is still misleading.

**Comment by Thiez** [comment]
Thanks! The new documentation looks great to me. The original issue was not blocking for me so I don't mind that it took a while to get fixed :-)
