### ISSUE TITLE
In Outlook, how can I switch view from a task pane add-in to a module extension?

### ISSUE THREAD

**Issue by Nachasic** [OfficeDev/office-js-docs-reference#317]
We're working with task pane add-ins and module extension add-ins in Outlook.

We need to be able to display a button in a task pane, that changes Outlook's view to a page in our module extension when clicked, passing information from the task pane's context to it.

Is this possible, and if so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76004e57-4c78-a1d9-7fd6-1adb6635094e
* Version Independent ID: 7ed56398-e6be-f624-f76d-8982c36fa81a
* Content: [Office.UI interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=office-js#displaydialogasync-startaddress--options--callback-)
* Content Source: [docs/docs-ref-autogen/office/office.ui.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office.ui.yml)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@Nachasic thanks for your interest in Office Add-ins development. If you haven't already done so, I'd recommend that you post this question to Stack Overflow, tagged with the [outlook-web-addins](https://stackoverflow.com/questions/tagged/outlook-web-addins) tag. I'm going to close this issue here in **OfficeDev/office-js-docs-reference**, since this is a how-to question and not a documentation bug (and issues here are intended for reporting problems with the API *documentation*). How-to questions like this are well-suited for Stack Overflow, where you'll not only be able to reach a broader audience of folks who have expertise in the area, but will also enable others to benefit from any answers that are provided there.
