### ISSUE TITLE
WorksheetProtectionData

### ISSUE THREAD

**Issue by sivakrishna0205** [OfficeDev/office-js-docs-reference#351]
worksheet protection is not working in officejs Javascript library i'm using.
code:
let password = await passwordHandler();
passwordHelper(password);
await Excel.run(async (context) =&gt; {
    let activeSheet = context.workbook.worksheets.getActiveWorksheet();
    activeSheet.load("protection/protected");

    await context.sync();

    if (!activeSheet.protection.protected) {
        activeSheet.protection.protect(null, password);
    }
});
throwing internal server error using with side loaded web adding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa1ff77c-ae4b-c6ca-706e-b49507ebbbd8
* Version Independent ID: 7a4a4875-c7b0-b873-24f0-84f09b2cd12d
* Content: [Excel.WorksheetProtection class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheetprotection?view=office-js#feedback)
* Content Source: [docs/docs-ref-autogen/excel/excel.worksheetprotection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.worksheetprotection.yml)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @sivakrishna0205,

Thanks for raising this issue with our sample code. Can you share your implementation of `passwordHelper` with us? Any error logs would be helpful too. 

We have a sample implementation in our [ScriptLab](https://github.com/OfficeDev/script-lab) sample. It's the "DataProtection" sample, which can also been found [here](https://github.com/OfficeDev/office-js-snippets/blob/master/samples/excel/50-workbook/data-protection.yaml).

**Comment by sivakrishna0205** [comment]
Hi @AlexJerabek ,
I have executed  ScriptLab Add-in sample examples in my Excel 2016 desktop version. Its throwing following exception.
![image](https://user-images.githubusercontent.com/15037598/54421055-9cbb4900-4731-11e9-95f4-e714f1a90ed7.png)
Error: c {description: "The property 'protected' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.", name: "RichApi.Error"....

**Comment by Reezaali** [comment]
@sivakrishna0205 sorry to hear it's still not working. Can you share the Excel version and build number please?

**Comment by sivakrishna0205** [comment]
> @sivakrishna0205 sorry to hear it's still not working. Can you share the Excel version and build number please?

@Reezaali 

![image](https://user-images.githubusercontent.com/15037598/54530666-5e2fc380-49a9-11e9-9ac0-25487cfdf449.png)

**Comment by AlexJerabek** [comment]
Hi @sivakrishna0205,

Thanks for the information. Office 2016 only supports the Excel APIs up through requirement set 1.1. You can view [platform support here](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-in-availability) and the support of [specific Excel builds here](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets).

[WorkbookProtection](https://docs.microsoft.com/javascript/api/excel/excel.workbookprotection) was introduced in ExcelAPI 1.7. That functionality will work in Office Online and Office 365.

I'm going to close the issue since the error is expected. Please respond to this thread if you there's a documentation issue around requirement sets or related information. Thanks!
