### ISSUE TITLE
Can't set Excel.Range.formulas and Excel.Range.values with single string value

### ISSUE THREAD

**Issue by redcirkle** [OfficeDev/office-js-docs-reference#578]
## Article URL
https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#feedback

## Issue
Many Excel.Range properties like `formulas`, `values`, and `numberFormat` include text that says "When setting <PROPERTY> to a range, the <PROPERTY> argument can be either a single value (string, number or boolean) or a two-dimensional array. If the argument is a single value, it will be applied to all cells in the range."

As a suggestion, I think the documentation should provide an example of how to make use of this "single value" option. From my testing, I've determined you need to set the "single value" like the following:
`range.numberFormat = [["MM/DD/YYY"]];`

I think this is a little unintuitive, and I imagine many other people like myself will try to set the 2D array to a single value only to have the compiler complain. An example of how to do this properly for at least one of the properties would clarify a lot. 

My larger problem though, is that I've only been able to set `numberFormat` like this. I've written code similar to the line above for ranges where I want to set `formulas` or `values`, and my functions stop executing once they reach these lines. Does this feature work for these other properties? Is there a different way I should be setting them?

**Comment by AlexJerabek** [comment]
Hi @redcirkle, 

Thanks for raising this issue. I've added a work item to add more samples around these scenarios.

As for your difficulties setting range properties with single values, have you posted your questions on [Stack Overflow](http://stackoverflow.com/questions/tagged/office-js)? I'm also tagging @wandyezj to investigate.

**Comment by AlexJerabek** [comment]
Hi @redcirkle, 

Thank you for your patience. 

It does appear you can set values, formulas, and numberFormats with a single string (not a single-celled 2D-array). Here's the gist showing that: https://gist.github.com/AlexJerabek/df7e9ca516dca8a4312f94e7459d8756

```
range.values = "1";
range.formulas = "=A1+A2";
range.numberFormat = "MM/DD/YYYY";
```

Of course, that doesn't compile in TypeScript, since those properties are all listed as type `any[][]` in the type definition file. This appears to be a bug with the type definition file. I'll wrap up my investigation with the product team, which will likely result in me moving this issue to the office-js repo.

Hopefully, this is enough to unblock you. Please let me know if there's anything else with which I can help you.

**Comment by AlexJerabek** [comment]
Hi @redcirkle, 

We have updated the documentation to remove mentions of setting array-based properties with single values. While it's possible, it goes against the TypeScript definitions and will be difficult to document. We're investigating adding methods to deliver the same functionality in an easily explainable and TypeScript-friendly manner.
