### ISSUE TITLE
Examples for Properties read and write during file upload

### ISSUE THREAD

**Issue by Ofer-Gal** [OfficeDev/office-js-docs-reference#665]
Where can I find examples of Properties read and write between the file upload and save somewhere else?

I am using the @progress/kendo-react-upload component for the upload and the file.getRawFile() to get the bytes and save them in SharePoint.
I would like to read and write some properties like title, tag and maybe add a custom property before the save to Sharepoint.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9a41c03-0eb8-cc64-1b30-cae42524ab83
* Version Independent ID: 30464d68-3c50-da53-7bd7-443ba5b801b6
* Content: [Word.DocumentProperties class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.documentproperties?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.documentproperties.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.documentproperties.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Ofer-Gal, 

To use properties with Office JavaScript library, you're going to have to read and write them while the document is open in Office (Word, in this case). If you'd like to read and write them server-side, you'll need to work with the [Open XML](https://docs.microsoft.com/office/open-xml/open-xml-sdk).

This level of programming question feels appropriate for [Stack Overflow](http://stackoverflow.com/questions/tagged/office-js). I'd recommend asking this question there, so it will be visible to a wider audience. Be sure to tag the question with "office-js".

Because this is out of the scope of the Office JavaScript libraries, I'm going to close the issue. Please respond to the thread if you disagree.
