### ISSUE TITLE
customXmlParts is undefined

### ISSUE THREAD

**Issue by hyzhang** [OfficeDev/office-js-docs-reference#692]
try to access customXmlParts	by calling Office.context.document.customXmlParts, but in runtime, it's undefined, same question was asked almost 3 years ago(https://stackoverflow.com/questions/44808543/unable-to-use-office-context-document-customxmlparts-addasync-method) but no answer, any idea please? 
my office-js version is 1.0.52 and seems customXmlParts is included

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80b0c0b-0647-036d-9193-4be6c67edf21
* Version Independent ID: db81f510-204a-d07b-f02f-6b0e83f1f592
* Content: [Office.Document interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=word-js-preview#remarks)
* Content Source: [docs/docs-ref-autogen/office/office/office.document.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.document.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
See my answer to the Stack Overflow question. Since we use the issues of the repo to track problems with the documentation, not technical issues, I'm going to close this. Please follow-up as needed on the Stack question. If you are getting this error in a task pane or FunctionFile (that is; not in the Dialog), then please create a new Stack question. Thanks.
