### ISSUE TITLE
Insert a mailMerge field into a word document

### ISSUE THREAD

**Issue by Sunpay** [OfficeDev/office-js-docs-reference#697]
I would like to insert MailMerges field into a Word document from a Word add-in. Previously I used [Visual Studio Tools for Office](https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.tools.word.document.mailmerge?view=vsto-2017).

As an example:
_wordApp.ActiveDocument.MailMerge.Fields.Add(_wordApp.Selection.Range, fieldName);

I have looked at the newer JavaScript add-in framework for building add-ins (https://docs.microsoft.com/en-us/office/dev/add-ins/word/) but it wasn't obvious to me if I could use this to add a mail merge field?

I would really appreciate your input.

## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/word

**Comment by AlexJerabek** [comment]
Hi @Sunpay, 

There is not an equivalent to the MailMerge object in the Word JavaScript APIs. You might be able to do this with OpenXML (I found [this sample](http://www.jarredcapellman.com/2012/10/22/c-openxml-mail-merge-complete-example/) after a quick search, though I can't verify its accuracy).

I'd recommend two things:
- Post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) with the office-js tag. That will let a broader audience of experts help you and allow others to find the answers they provide.
- Visit [UserVoice](https://officespdev.uservoice.com/) and request or upvote this feature for Word add-ins. We use UserVoice to prioritize feature requests, so the more popular a request is, the sooner we'll get to it.

Since there's not much we can do to help in the Office JS documentation, I'm going to close this issue.
