### ISSUE TITLE
What is the purpose of OfficeRuntime.storage if there is e.g. LocalStorage & IndexedDB

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js-docs-reference#702]
I know that it is possible to use IndexedDB and LocalStorage inside an Office add-in (and I do, as I need to cache many megabytes of data for formula calculation).

What is the purpose of OfficeRuntime.storage as opposed to those browser-provided storage entities?

Would be good to clarify in the article.

**Comment by mscharlock** [comment]
Yes, it is possible to use LocalStorage inside an add-in. However, if you are using custom functions (which it sounds like you might be), you can't use that, because custom functions runs in a separate runtime that doesn't have access to the DOM. If you're trying to cache information from a formula calculation, you'll have to save it in OfficeRuntime.storage, which is accessible to both custom functions and the "regular web runtime" that all add-ins except custom functions use. Luckily there is a new way to share data, which is to use Shared Runtime in custom functions. You need to change your manifest in order to use it. There's details on how to use Shared Runtime and configure it [here.](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime) Hope that answers your question - let me know if that doesn't answer your questions. Also, what article are you referring to? It would be helpful for me if you can provide a link so I can look at the docs and try to make this as clear as possible. Thanks!
