### ISSUE TITLE
adding a setting using  'context.workbook.settings.add' is not available if we close and open the application

### ISSUE THREAD

**Issue by intellectyxArria** [OfficeDev/office-js-docs-reference#802]
[Enter feedback here]

Assume the following scenario where I save a setting with key as **_type_** and value as '**_DemoWoekbook_**' context.workbook.settings.add('type', 'DemoWorkbook'). When I close the document and again open it I couldn't find these settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cbceac7-f2e9-8d65-e8cc-a50e648d7f1a
* Version Independent ID: b7fd6891-ec2f-9c68-45fa-b0bf864d25b9
* Content: [Excel.SettingCollection class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.settingcollection?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.settingcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.settingcollection.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @intellectyxArria, thank you for submitting an issue! Workbook settings are unique to a single workbook + add-in pair. This [Access document settings section](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks#access-document-settings) has more information. If this doesn't help resolve your issue, could you provide the complete add-in code you're using, so that we can reproduce the issue? 

Thanks again, 
-Alison
