### ISSUE TITLE
Can't insert different pages(footer)  numbers in Word javascript api

### ISSUE THREAD

**Issue by takenaldo** [OfficeDev/office-js-docs-reference#905]
i am trying to add incremental page  numbers to my word document,but the Word add-in API didn't have a clear way to do that, please fix this issue

**Comment by AlexJerabek** [comment]
Hi @takenaldo, 

Thanks for reaching out. To request features, such as new Word APIs, please visit [UserVoice](https://officespdev.uservoice.com/) and create a new suggestion (or upvote an existing one). This lets our team prioritize feature requests based on community interest. I'll also tag @AbidRahman-MSFT, since he has been tracking new feature requests for Word Add-ins. 

As a workaround, you could explore using [OOXML](https://docs.microsoft.com/office/dev/add-ins/word/create-better-add-ins-for-word-with-office-open-xml) to insert the page numbers. That might be something the community on [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) can help with as well.

I'm going to close the issue, since there's nothing actionable to be done in the Office JavaScript API documentation.

**Comment by takenaldo** [comment]
Thank a lot. I would like ask one more question. Can I get chance to sell
my add-in to microsoft or any other company?

**Comment by AlexJerabek** [comment]
Hi @takenaldo, 

You can learn about publishing options for your add-in from the article [Deploy and publish Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish). That will help you decide what the best end result for your add-in is, whether it's selling through AppSource. monetizing as a [SaSS solution](https://docs.microsoft.com/en-us/office/dev/store/monetize-addins-through-microsoft-commercial-marketplace), or working directly with a third-party company to deliver them your solution.
