### ISSUE TITLE
PowerPoint API reference to voice-over narration is missing 

### ISSUE THREAD

**Issue by chaaridev** [OfficeDev/office-js-docs-reference#909]
Hi,
A reference to voice-over narration sound feature  is missing.
Is this feature supported by the PowerPoint API ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1e60002-ed9c-1329-e238-6827761ce9c6
* Version Independent ID: e2485f2c-aac8-aa3f-8880-d25812812d40
* Content: [powerpoint package - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/powerpoint?view=powerpoint-js-preview)
* Content Source: [docs/docs-ref-autogen/powerpoint/powerpoint.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint/powerpoint.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @chaaridev, 

Narration control is not currently supported by the PowerPoint JS APIs for Office Add-ins. I'd recommend heading over to [UserVoice](https://officespdev.uservoice.com/) to make or upvote the feature request. We use UserVoice to prioritize community requests when deciding which new features to work on.

I'm going to close the issue now, since there's nothing actionable to be done in the documentation. Thanks!
