### ISSUE TITLE
missing apis

### ISSUE THREAD

**Issue by AkmarNafi** [OfficeDev/office-js-docs-reference#935]
I could not find PowerPoint APIs for fetching font properties like color, size etc  similar to  Word and Excel APIs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae8458bf-959c-a4f5-63b0-25ac4bcb66e1
* Version Independent ID: e2485f2c-aac8-aa3f-8880-d25812812d40
* Content: [powerpoint package - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/powerpoint?view=powerpoint-js-1.1)
* Content Source: [docs/docs-ref-autogen/powerpoint_1_1/powerpoint.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint_1_1/powerpoint.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @AkmarNafi, 

Thanks for your interest in PowerPoint Add-ins. Unfortunately, font APIs, like those in Word and Excel, are not yet implemented for PowerPoint.

We are actively developing the PowerPoint API surface. I'd recommend raising this need on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-addins-dev.html). That way, other members of the community can see and upvote the feature request. This helps our development team prioritize new APIs. I'll also forward this thread to the product team for awareness.

Since there's no actionable documentation steps, I'm going to close the issue. Please feel free to create another issue or respond to this thread if you have further questions.
